require("plugins.ai")
require("plugins.flash")
require("plugins.formatting")
-- require("plugins.hardtime")
require("plugins.lsp-config")
require("plugins.mini")
require("plugins.snacks")
require("plugins.treesitter")
require("plugins.tokyonight")
require("plugins.whichkey")
